name: 'SHS CICD'

on: push

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: |
          cd v1/api
          go build

      - name: Vet & Lint
        run: |
          cd v1/api
          go vet
          golint

      - name: Test
        run: |
          cd v1/api
          go test -v -coverprofile=coverage.out
          go tool cover -func=coverage.out
